
resources:
  repositories:
  - repository: simplnx
    type: github
    endpoint: BlueQuartzSoftware
    name: BlueQuartzSoftware/simplnx

trigger:
  - develop

jobs:
- job:
  strategy:
    matrix:
      macOS:
        imageName: Darwin
      Windows:
        imageName: Windows_NT
      Linux:
        imageName: Linux

  pool:
    name: BlueQuartz Self Hosted
    demands:
      - Agent.OS -equals $(imageName)
      - BQ.COMPLEX
 
  workspace:
    clean: all

  timeoutInMinutes: 120

  variables:
    complex_source_dir: $(Build.Repository.LocalPath)
    build_type: Release
    dream3d_data_dir: $(Agent.WorkFolder)/DREAM3D_Data

  steps:
  - checkout: self
    submodules: true

  - script: |
      echo System.PullRequest.SourceBranch=$(System.PullRequest.SourceBranch)
      echo System.PullRequest.PullRequestNumber=$(System.PullRequest.PullRequestNumber)
      echo Build.SourceBranchName=$(Build.SourceBranchName)
      echo Build.Repository.Name=$(Build.Repository.Name)
      echo Build.Repository.Uri=$(Build.Repository.Uri)
      echo Agent.WorkFolder=$(Agent.WorkFolder)
      echo Agent.OS=$(Agent.OS)
      echo Build.BuildNumber=$(Build.BuildNumber)
    displayName: 'Dump Azure Variables'

  - powershell: |
      $DLL_PATH = Get-Content $(Agent.WorkFolder)/NX_DLL_PATH.txt -Raw
      Write-Host "##vso[task.prependpath]$DLL_PATH"
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: Appending to PATH

  - script: |
      cmake -S $(complex_source_dir) -B $(Build.BinariesDirectory) -G Ninja -DCMAKE_BUILD_TYPE:STRING=$(build_type) -DDREAM3D_DATA_DIR=$(dream3d_data_dir) -C $(Agent.WorkFolder)/NX.cmake -DBUILDNAME:STRING="simplnx-$(Agent.MachineName)-$(Agent.OS)-PR$(System.PullRequest.PullRequestNumber)"

    displayName: Configure COMPLEX

  - script: |
      cmake --build $(Build.BinariesDirectory) --config $(build_type) --target all
    displayName: Build COMPLEX

  - script: |
      cd $(Build.BinariesDirectory)
      cpack -C $(build_type) --verbose
    continueOnError: true
    displayName: Packing COMPLEX

  - script: |
      cd $(Build.BinariesDirectory)
      ctest -C $(build_type) -D Experimental --timeout 7200 -DCTEST_SITE:STRING=$(Agent.MachineName).bluequartz.net -Ddashboard_source_name:STRING=DREAM3D
    continueOnError: true
    displayName: Testing COMPLEX

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: CTest
      testResultsFiles: $(Build.BinariesDirectory)/Testing/*/Test.xml
      testRunTitle: CTest_$(Agent.Name)_$(Agent.OS)
      failTaskOnFailedTests: false
    displayName: Publish Test Results
